#------------project configuration start----------------#
chat_llm: &chat_llm
  type: maas
  base_url: https://dashscope.aliyuncs.com/compatible-mode/v1/
  api_key: sk
  model: qwen2.5-72b-instruct
  enable_check: false

reason_llm: &reason_llm
  type: maas
  base_url: https://dashscope.aliyuncs.com/compatible-mode/v1/
  api_key: sk
  model: qwen2.5-72b-instruct
  stream: true

llm: *reason_llm

vectorize_model: &vectorize_model
  api_key: sk
  base_url: https://api.siliconflow.cn/v1/
  model: BAAI/bge-m3
  type: openai
  vector_dimensions: 1024
  enable_check: false
vectorizer: *vectorize_model

log:
  level: INFO

project:
  biz_scene: default
  host_addr: http://127.0.0.1:8887
  id: '3'
  language: en
  namespace: MuSiQue
#------------project configuration end----------------#

#------------kag-builder configuration start----------------#
kag_builder_pipeline:
  chain:
    type: unstructured_builder_chain # kag.builder.default_chain.DefaultUnstructuredBuilderChain
    extractor:
      type: naive_rag_extractor # kag.builder.component.extractor.schema_free_extractor.SchemaFreeExtractor
      llm: *chat_llm
      ner_prompt:
        type: default_ner # kag.builder.prompt.default.ner.OpenIENERPrompt
      std_prompt:
        type: default_std # kag.builder.prompt.default.std.OpenIEEntitystandardizationdPrompt
      triple_prompt:
        type: default_triple # kag.builder.prompt.default.triple.OpenIETriplePrompt
    reader:
      type: dict_reader # kag.builder.component.reader.dict_reader.DictReader
    post_processor:
      type: kag_post_processor # kag.builder.component.postprocessor.kag_postprocessor.KAGPostProcessor
    splitter:
      type: length_splitter # kag.builder.component.splitter.length_splitter.LengthSplitter
      split_length: 100000
      window_length: 0
    vectorizer:
      type: batch_vectorizer # kag.builder.component.vectorizer.batch_vectorizer.BatchVectorizer
      vectorize_model: *vectorize_model
    writer:
      type: memory_graph_writer
  scanner:
    type: musique_dataset_scanner # kag.builder.component.scanner.dataset_scanner.MusiqueCorpusScanner
#------------kag-builder configuration end----------------#

#------------kag-solver configuration start----------------#

reasoner: &reasoner_conf
  type: long_context_reasoner
  llm: *chat_llm
  memory_graph_path: 
    /Users/simplex/Src/libs/opensource/KAG/kag/open_benchmark/musique/builder/ckpt/writer
  vectorize_model: *vectorize_model
  context_select_prompt:
    type: context_select_prompt
  context_select_llm: *reason_llm


kag_solver_pipeline:
  type: kag_static_pipeline
  planner:
    type: kag_static_planner
    llm: *chat_llm
    plan_prompt:
      type: retriever_static_planning
    rewrite_prompt:
      type: default_query_rewrite
  executors:
    - *reasoner_conf
  generator:
    type: llm_generator_with_thought
    llm_client: *chat_llm
#------------kag-solver configuration end----------------#
