###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
from typing import Any, Dict, List, Optional, Union, TypedDict, Type, Literal
from typing_extensions import NotRequired

import baml_py

from . import types
from .types import Checked, Check
from .type_builder import TypeBuilder


class BamlCallOptions(TypedDict, total=False):
    tb: NotRequired[TypeBuilder]
    client_registry: NotRequired[baml_py.baml_py.ClientRegistry]


class AsyncHttpRequest:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager

    
    async def DeduceChoice(
        self,
        instruction: str,memory: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "DeduceChoice",
        {
          "instruction": instruction,
          "memory": memory,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def DeduceEntail(
        self,
        instruction: str,memory: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "DeduceEntail",
        {
          "instruction": instruction,
          "memory": memory,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def DeduceExtractor(
        self,
        instruction: str,memory: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "DeduceExtractor",
        {
          "instruction": instruction,
          "memory": memory,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def DeduceJudge(
        self,
        instruction: str,memory: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "DeduceJudge",
        {
          "instruction": instruction,
          "memory": memory,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def DeduceMultiChoice(
        self,
        instruction: str,memory: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "DeduceMultiChoice",
        {
          "instruction": instruction,
          "memory": memory,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def ExpressionBuilder(
        self,
        now: str,question: str,context: str,error: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "ExpressionBuilder",
        {
          "now": now,
          "question": question,
          "context": context,
          "error": error,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def LFStaticPlanningPrompt(
        self,
        now: str,case: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "LFStaticPlanningPrompt",
        {
          "now": now,
          "case": case,
          "query": query,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def LogicFromPlan(
        self,
        question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "LogicFromPlan",
        {
          "question": question,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def MultiHopGenerator(
        self,
        context: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "MultiHopGenerator",
        {
          "context": context,
          "query": query,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def OutputQuestion(
        self,
        context: str,question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "OutputQuestion",
        {
          "context": context,
          "question": question,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def QueryRewritePrompt(
        self,
        context: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "QueryRewritePrompt",
        {
          "context": context,
          "query": query,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def QuestionNER(
        self,
        schema: List[str],input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "QuestionNER",
        {
          "schema": schema,
          "input": input,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def ReferenceGenerator(
        self,
        now: str,content: str,ref: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "ReferenceGenerator",
        {
          "now": now,
          "content": content,
          "ref": ref,
          "query": query,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def RespExtractor(
        self,
        supporting_fact: str,instruction: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "RespExtractor",
        {
          "supporting_fact": supporting_fact,
          "instruction": instruction,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def RespGenerator(
        self,
        memory: str,instruction: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "RespGenerator",
        {
          "memory": memory,
          "instruction": instruction,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def RespJudge(
        self,
        memory: str,instruction: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "RespJudge",
        {
          "memory": memory,
          "instruction": instruction,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def RespReflector(
        self,
        memory: str,instruction: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "RespReflector",
        {
          "memory": memory,
          "instruction": instruction,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def RespVerifier(
        self,
        sub_instruction: str,supporting_fact: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "RespVerifier",
        {
          "sub_instruction": sub_instruction,
          "supporting_fact": supporting_fact,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def RewriteSubQuery(
        self,
        history_qa: str,question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "RewriteSubQuery",
        {
          "history_qa": history_qa,
          "question": question,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def RewriteSubTaskQuery(
        self,
        content: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "RewriteSubTaskQuery",
        {
          "content": content,
          "input": input,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def SPORetrieval(
        self,
        question: str,mention: str,candis: List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "SPORetrieval",
        {
          "question": question,
          "mention": mention,
          "candis": candis,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def SelfCognition(
        self,
        question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "SelfCognition",
        {
          "question": question,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def SolveQuestion(
        self,
        question: str,history: str,docs: str,knowledge_graph: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "SolveQuestion",
        {
          "question": question,
          "history": history,
          "docs": docs,
          "knowledge_graph": knowledge_graph,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def SolveQuestionNoDocs(
        self,
        question: str,history: str,knowledge_graph: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "SolveQuestionNoDocs",
        {
          "question": question,
          "history": history,
          "knowledge_graph": knowledge_graph,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def SolveQuestionNoSPO(
        self,
        question: str,history: str,docs: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "SolveQuestionNoSPO",
        {
          "question": question,
          "history": history,
          "docs": docs,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    


class AsyncHttpStreamRequest:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager

    
    async def DeduceChoice(
        self,
        instruction: str,memory: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "DeduceChoice",
        {
          "instruction": instruction,
          "memory": memory,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def DeduceEntail(
        self,
        instruction: str,memory: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "DeduceEntail",
        {
          "instruction": instruction,
          "memory": memory,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def DeduceExtractor(
        self,
        instruction: str,memory: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "DeduceExtractor",
        {
          "instruction": instruction,
          "memory": memory,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def DeduceJudge(
        self,
        instruction: str,memory: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "DeduceJudge",
        {
          "instruction": instruction,
          "memory": memory,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def DeduceMultiChoice(
        self,
        instruction: str,memory: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "DeduceMultiChoice",
        {
          "instruction": instruction,
          "memory": memory,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def ExpressionBuilder(
        self,
        now: str,question: str,context: str,error: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "ExpressionBuilder",
        {
          "now": now,
          "question": question,
          "context": context,
          "error": error,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def LFStaticPlanningPrompt(
        self,
        now: str,case: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "LFStaticPlanningPrompt",
        {
          "now": now,
          "case": case,
          "query": query,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def LogicFromPlan(
        self,
        question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "LogicFromPlan",
        {
          "question": question,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def MultiHopGenerator(
        self,
        context: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "MultiHopGenerator",
        {
          "context": context,
          "query": query,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def OutputQuestion(
        self,
        context: str,question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "OutputQuestion",
        {
          "context": context,
          "question": question,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def QueryRewritePrompt(
        self,
        context: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "QueryRewritePrompt",
        {
          "context": context,
          "query": query,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def QuestionNER(
        self,
        schema: List[str],input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "QuestionNER",
        {
          "schema": schema,
          "input": input,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def ReferenceGenerator(
        self,
        now: str,content: str,ref: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "ReferenceGenerator",
        {
          "now": now,
          "content": content,
          "ref": ref,
          "query": query,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def RespExtractor(
        self,
        supporting_fact: str,instruction: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "RespExtractor",
        {
          "supporting_fact": supporting_fact,
          "instruction": instruction,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def RespGenerator(
        self,
        memory: str,instruction: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "RespGenerator",
        {
          "memory": memory,
          "instruction": instruction,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def RespJudge(
        self,
        memory: str,instruction: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "RespJudge",
        {
          "memory": memory,
          "instruction": instruction,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def RespReflector(
        self,
        memory: str,instruction: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "RespReflector",
        {
          "memory": memory,
          "instruction": instruction,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def RespVerifier(
        self,
        sub_instruction: str,supporting_fact: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "RespVerifier",
        {
          "sub_instruction": sub_instruction,
          "supporting_fact": supporting_fact,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def RewriteSubQuery(
        self,
        history_qa: str,question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "RewriteSubQuery",
        {
          "history_qa": history_qa,
          "question": question,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def RewriteSubTaskQuery(
        self,
        content: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "RewriteSubTaskQuery",
        {
          "content": content,
          "input": input,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def SPORetrieval(
        self,
        question: str,mention: str,candis: List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "SPORetrieval",
        {
          "question": question,
          "mention": mention,
          "candis": candis,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def SelfCognition(
        self,
        question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "SelfCognition",
        {
          "question": question,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def SolveQuestion(
        self,
        question: str,history: str,docs: str,knowledge_graph: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "SolveQuestion",
        {
          "question": question,
          "history": history,
          "docs": docs,
          "knowledge_graph": knowledge_graph,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def SolveQuestionNoDocs(
        self,
        question: str,history: str,knowledge_graph: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "SolveQuestionNoDocs",
        {
          "question": question,
          "history": history,
          "knowledge_graph": knowledge_graph,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def SolveQuestionNoSPO(
        self,
        question: str,history: str,docs: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "SolveQuestionNoSPO",
        {
          "question": question,
          "history": history,
          "docs": docs,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    


__all__ = ["AsyncHttpRequest", "AsyncHttpStreamRequest"]