###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing_extensions import TypeAlias
from typing import Dict, Generic, List, Optional, TypeVar, Union, Literal

from . import types
from .types import Checked, Check

###############################################################################
#
#  These types are used for streaming, for when an instance of a type
#  is still being built up and any of its fields is not yet fully available.
#
###############################################################################

T = TypeVar('T')
class StreamState(BaseModel, Generic[T]):
    value: T
    state: Literal["Pending", "Incomplete", "Complete"]


class Answer(BaseModel):
    answer: Optional[str] = None

class AnswerQuestion(BaseModel):
    answer: Optional[str] = None

class Builder(BaseModel):
    python_code: Optional[str] = None
    not_known: Optional[bool] = None

class Choice(BaseModel):
    choice: Optional[str] = None
    no_available_information: Optional[bool] = None

class Cognition(BaseModel):
    is_cognition_question: Optional[bool] = None

class Entail(BaseModel):
    entail: Optional[str] = None
    no_available_information: Optional[bool] = None

class Extractor(BaseModel):
    extractor: Optional[str] = None
    no_relevant_information: Optional[bool] = None

class Judge(BaseModel):
    assessable: Optional[bool] = None
    no_available_information: Optional[bool] = None

class Judgement(BaseModel):
    answer: Optional[bool] = None

class LFStaticPlan(BaseModel):
    idea: Optional[str] = None
    step: Optional[str] = None
    action: Optional[str] = None

class LFStaticPlanning(BaseModel):
    python_code: Optional[str] = None
    not_known: Optional[bool] = None

class LFStaticPlans(BaseModel):
    plans: List["LFStaticPlan"]

class Multi(BaseModel):
    option: Optional[str] = None
    no_available_information: Optional[bool] = None

class MultiAnswer(BaseModel):
    thought: Optional[str] = None
    answer: Optional[str] = None

class Passage(BaseModel):
    passage: Optional[str] = None

class Plan(BaseModel):
    step: Optional[str] = None
    action: Optional[str] = None

class Plans(BaseModel):
    plans: List["Plan"]

class QNer(BaseModel):
    name: Optional[str] = None
    category: Optional[str] = None

class QNers(BaseModel):
    output: List["QNer"]

class RefAnswer(BaseModel):
    answer: Optional[bool] = None

class Reflection(BaseModel):
    thought_questions: List[str]

class Rewrite(BaseModel):
    rewritten_question: Optional[bool] = None

class RewriteQuery(BaseModel):
    rewritten_question: Optional[bool] = None

class RewrittenPrompt(BaseModel):
    query: Optional[bool] = None

class SPOs(BaseModel):
    spos: List[str]

class Solve(BaseModel):
    answer: Optional[str] = None

class SolveNoDocs(BaseModel):
    answer: Optional[str] = None

class SolveNoSPO(BaseModel):
    answer: Optional[str] = None

class Verifier(BaseModel):
    answer: Optional[str] = None
    answered: Optional[bool] = None
