###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
from typing import Any, Dict, List, Optional, TypeVar, Union, TypedDict, Type, Literal, cast
from typing_extensions import NotRequired
import pprint

import baml_py
from pydantic import BaseModel, ValidationError, create_model

from . import partial_types, types
from .types import Checked, Check
from .type_builder import TypeBuilder
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
from .sync_request import HttpRequest, HttpStreamRequest
from .parser import LlmResponseParser, LlmStreamParser

OutputType = TypeVar('OutputType')


# Define the TypedDict with optional parameters having default values
class BamlCallOptions(TypedDict, total=False):
    tb: NotRequired[TypeBuilder]
    client_registry: NotRequired[baml_py.baml_py.ClientRegistry]
    collector: NotRequired[Union[baml_py.baml_py.Collector, List[baml_py.baml_py.Collector]]]


class BamlSyncClient:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager
    __stream_client: "BamlStreamClient"
    __http_request: "HttpRequest"
    __http_stream_request: "HttpStreamRequest"
    __llm_response_parser: LlmResponseParser
    __baml_options: BamlCallOptions

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager, baml_options: Optional[BamlCallOptions] = None):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager
      self.__stream_client = BamlStreamClient(self.__runtime, self.__ctx_manager, baml_options)
      self.__http_request = HttpRequest(self.__runtime, self.__ctx_manager)
      self.__http_stream_request = HttpStreamRequest(self.__runtime, self.__ctx_manager)
      self.__llm_response_parser = LlmResponseParser(self.__runtime, self.__ctx_manager)
      self.__llm_stream_parser = LlmStreamParser(self.__runtime, self.__ctx_manager)
      self.__baml_options = baml_options or {}

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    def with_options(
      self,
      tb: Optional[TypeBuilder] = None,
      client_registry: Optional[baml_py.baml_py.ClientRegistry] = None,
      collector: Optional[Union[baml_py.baml_py.Collector, List[baml_py.baml_py.Collector]]] = None,
    ) -> "BamlSyncClient":
      """
      Returns a new instance of BamlSyncClient with explicitly typed baml options
      for Python 3.8 compatibility.
      """
      new_options: BamlCallOptions = self.__baml_options.copy()

      # Override if any keyword arguments were provided.
      if tb is not None:
          new_options["tb"] = tb
      if client_registry is not None:
          new_options["client_registry"] = client_registry
      if collector is not None:
          new_options["collector"] = collector
      return BamlSyncClient(self.__runtime, self.__ctx_manager, new_options)

    
    def DeduceChoice(
        self,
        instruction: str,memory: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Choice:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "DeduceChoice",
        {
          "instruction": instruction,"memory": memory,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.Choice, raw.cast_to(types, types, partial_types, False))
    
    def DeduceEntail(
        self,
        instruction: str,memory: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Entail:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "DeduceEntail",
        {
          "instruction": instruction,"memory": memory,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.Entail, raw.cast_to(types, types, partial_types, False))
    
    def DeduceExtractor(
        self,
        instruction: str,memory: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Extractor:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "DeduceExtractor",
        {
          "instruction": instruction,"memory": memory,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.Extractor, raw.cast_to(types, types, partial_types, False))
    
    def DeduceJudge(
        self,
        instruction: str,memory: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Judge:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "DeduceJudge",
        {
          "instruction": instruction,"memory": memory,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.Judge, raw.cast_to(types, types, partial_types, False))
    
    def DeduceMultiChoice(
        self,
        instruction: str,memory: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Multi:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "DeduceMultiChoice",
        {
          "instruction": instruction,"memory": memory,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.Multi, raw.cast_to(types, types, partial_types, False))
    
    def ExpressionBuilder(
        self,
        now: str,question: str,context: str,error: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Builder:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "ExpressionBuilder",
        {
          "now": now,"question": question,"context": context,"error": error,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.Builder, raw.cast_to(types, types, partial_types, False))
    
    def LFStaticPlanningPrompt(
        self,
        now: str,case: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> types.LFStaticPlans:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "LFStaticPlanningPrompt",
        {
          "now": now,"case": case,"query": query,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.LFStaticPlans, raw.cast_to(types, types, partial_types, False))
    
    def LogicFromPlan(
        self,
        question: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Plans:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "LogicFromPlan",
        {
          "question": question,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.Plans, raw.cast_to(types, types, partial_types, False))
    
    def MultiHopGenerator(
        self,
        context: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> types.MultiAnswer:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "MultiHopGenerator",
        {
          "context": context,"query": query,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.MultiAnswer, raw.cast_to(types, types, partial_types, False))
    
    def OutputQuestion(
        self,
        context: str,question: str,
        baml_options: BamlCallOptions = {},
    ) -> types.AnswerQuestion:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "OutputQuestion",
        {
          "context": context,"question": question,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.AnswerQuestion, raw.cast_to(types, types, partial_types, False))
    
    def QueryRewritePrompt(
        self,
        context: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RewrittenPrompt:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "QueryRewritePrompt",
        {
          "context": context,"query": query,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.RewrittenPrompt, raw.cast_to(types, types, partial_types, False))
    
    def QuestionNER(
        self,
        schema: List[str],input: str,
        baml_options: BamlCallOptions = {},
    ) -> types.QNers:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "QuestionNER",
        {
          "schema": schema,"input": input,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.QNers, raw.cast_to(types, types, partial_types, False))
    
    def QuestionSummary(
        self,
        history: str,question: str,docs: List[str],
        baml_options: BamlCallOptions = {},
    ) -> types.QuestionSummaryAnswer:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "QuestionSummary",
        {
          "history": history,"question": question,"docs": docs,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.QuestionSummaryAnswer, raw.cast_to(types, types, partial_types, False))
    
    def ReferenceGenerator(
        self,
        now: str,content: str,ref: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RefAnswer:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "ReferenceGenerator",
        {
          "now": now,"content": content,"ref": ref,"query": query,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.RefAnswer, raw.cast_to(types, types, partial_types, False))
    
    def RespExtractor(
        self,
        supporting_fact: str,instruction: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Passage:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "RespExtractor",
        {
          "supporting_fact": supporting_fact,"instruction": instruction,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.Passage, raw.cast_to(types, types, partial_types, False))
    
    def RespGenerator(
        self,
        memory: str,instruction: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Answer:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "RespGenerator",
        {
          "memory": memory,"instruction": instruction,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.Answer, raw.cast_to(types, types, partial_types, False))
    
    def RespJudge(
        self,
        memory: str,instruction: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Judgement:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "RespJudge",
        {
          "memory": memory,"instruction": instruction,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.Judgement, raw.cast_to(types, types, partial_types, False))
    
    def RespReflector(
        self,
        memory: str,instruction: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Reflection:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "RespReflector",
        {
          "memory": memory,"instruction": instruction,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.Reflection, raw.cast_to(types, types, partial_types, False))
    
    def RespVerifier(
        self,
        sub_instruction: str,supporting_fact: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Verifier:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "RespVerifier",
        {
          "sub_instruction": sub_instruction,"supporting_fact": supporting_fact,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.Verifier, raw.cast_to(types, types, partial_types, False))
    
    def RetrieverStaticPlanning(
        self,
        executors: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> types.STasks:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "RetrieverStaticPlanning",
        {
          "executors": executors,"query": query,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.STasks, raw.cast_to(types, types, partial_types, False))
    
    def RewriteSubQuery(
        self,
        history_qa: str,question: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RewriteQuery:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "RewriteSubQuery",
        {
          "history_qa": history_qa,"question": question,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.RewriteQuery, raw.cast_to(types, types, partial_types, False))
    
    def RewriteSubTaskQuery(
        self,
        content: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Rewrite:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "RewriteSubTaskQuery",
        {
          "content": content,"input": input,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.Rewrite, raw.cast_to(types, types, partial_types, False))
    
    def SPORetrieval(
        self,
        question: str,mention: str,candis: List[str],
        baml_options: BamlCallOptions = {},
    ) -> types.SPOs:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "SPORetrieval",
        {
          "question": question,"mention": mention,"candis": candis,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.SPOs, raw.cast_to(types, types, partial_types, False))
    
    def SPORetrievalDecompose(
        self,
        question: str,
        baml_options: BamlCallOptions = {},
    ) -> types.SPODecomposes:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "SPORetrievalDecompose",
        {
          "question": question,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.SPODecomposes, raw.cast_to(types, types, partial_types, False))
    
    def SelfCognition(
        self,
        question: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Cognition:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "SelfCognition",
        {
          "question": question,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.Cognition, raw.cast_to(types, types, partial_types, False))
    
    def SolveQuestion(
        self,
        question: str,history: str,docs: str,knowledge_graph: str,
        baml_options: BamlCallOptions = {},
    ) -> types.SolveNoSPO:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "SolveQuestion",
        {
          "question": question,"history": history,"docs": docs,"knowledge_graph": knowledge_graph,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.SolveNoSPO, raw.cast_to(types, types, partial_types, False))
    
    def SolveQuestionNoDocs(
        self,
        question: str,history: str,knowledge_graph: str,
        baml_options: BamlCallOptions = {},
    ) -> types.SolveNoDocs:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "SolveQuestionNoDocs",
        {
          "question": question,"history": history,"knowledge_graph": knowledge_graph,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.SolveNoDocs, raw.cast_to(types, types, partial_types, False))
    
    def SolveQuestionNoSPO(
        self,
        question: str,history: str,docs: str,
        baml_options: BamlCallOptions = {},
    ) -> types.SolveNoSPO:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "SolveQuestionNoSPO",
        {
          "question": question,"history": history,"docs": docs,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.SolveNoSPO, raw.cast_to(types, types, partial_types, False))
    
    def StaticPlanningPrompt(
        self,
        executors: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> types.STasks:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "StaticPlanningPrompt",
        {
          "executors": executors,"query": query,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.STasks, raw.cast_to(types, types, partial_types, False))
    
    def SubQuestionSummary(
        self,
        history: str,question: str,knowledge_graph: str,docs: List[str],
        baml_options: BamlCallOptions = {},
    ) -> types.SubQuestionSummaryAnswer:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "SubQuestionSummary",
        {
          "history": history,"question": question,"knowledge_graph": knowledge_graph,"docs": docs,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.SubQuestionSummaryAnswer, raw.cast_to(types, types, partial_types, False))
    
    def ToughtIterativePlanning(
        self,
        example_executors: str,query: str,context: str,executors: List[str],
        baml_options: BamlCallOptions = {},
    ) -> types.Executor:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "ToughtIterativePlanning",
        {
          "example_executors": example_executors,"query": query,"context": context,"executors": executors,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.Executor, raw.cast_to(types, types, partial_types, False))
    
    def ToughtThenAnswer(
        self,
        cur_question: str,questions: str,docs: str,
        baml_options: BamlCallOptions = {},
    ) -> types.TTA:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "ToughtThenAnswer",
        {
          "cur_question": cur_question,"questions": questions,"docs": docs,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.TTA, raw.cast_to(types, types, partial_types, False))
    
    def WithoutRefGenerator(
        self,
        now: str,content: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> types.WRG:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.call_function_sync(
        "WithoutRefGenerator",
        {
          "now": now,"content": content,"query": query,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.WRG, raw.cast_to(types, types, partial_types, False))
    



class BamlStreamClient:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager
    __baml_options: BamlCallOptions
    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager, baml_options: Optional[BamlCallOptions] = None):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager
      self.__baml_options = baml_options or {}

    
    def DeduceChoice(
        self,
        instruction: str,memory: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.Choice, types.Choice]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "DeduceChoice",
        {
          "instruction": instruction,
          "memory": memory,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.Choice, types.Choice](
        raw,
        lambda x: cast(partial_types.Choice, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.Choice, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def DeduceEntail(
        self,
        instruction: str,memory: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.Entail, types.Entail]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "DeduceEntail",
        {
          "instruction": instruction,
          "memory": memory,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.Entail, types.Entail](
        raw,
        lambda x: cast(partial_types.Entail, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.Entail, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def DeduceExtractor(
        self,
        instruction: str,memory: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.Extractor, types.Extractor]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "DeduceExtractor",
        {
          "instruction": instruction,
          "memory": memory,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.Extractor, types.Extractor](
        raw,
        lambda x: cast(partial_types.Extractor, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.Extractor, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def DeduceJudge(
        self,
        instruction: str,memory: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.Judge, types.Judge]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "DeduceJudge",
        {
          "instruction": instruction,
          "memory": memory,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.Judge, types.Judge](
        raw,
        lambda x: cast(partial_types.Judge, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.Judge, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def DeduceMultiChoice(
        self,
        instruction: str,memory: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.Multi, types.Multi]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "DeduceMultiChoice",
        {
          "instruction": instruction,
          "memory": memory,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.Multi, types.Multi](
        raw,
        lambda x: cast(partial_types.Multi, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.Multi, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def ExpressionBuilder(
        self,
        now: str,question: str,context: str,error: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.Builder, types.Builder]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "ExpressionBuilder",
        {
          "now": now,
          "question": question,
          "context": context,
          "error": error,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.Builder, types.Builder](
        raw,
        lambda x: cast(partial_types.Builder, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.Builder, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def LFStaticPlanningPrompt(
        self,
        now: str,case: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.LFStaticPlans, types.LFStaticPlans]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "LFStaticPlanningPrompt",
        {
          "now": now,
          "case": case,
          "query": query,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.LFStaticPlans, types.LFStaticPlans](
        raw,
        lambda x: cast(partial_types.LFStaticPlans, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.LFStaticPlans, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def LogicFromPlan(
        self,
        question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.Plans, types.Plans]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "LogicFromPlan",
        {
          "question": question,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.Plans, types.Plans](
        raw,
        lambda x: cast(partial_types.Plans, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.Plans, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def MultiHopGenerator(
        self,
        context: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.MultiAnswer, types.MultiAnswer]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "MultiHopGenerator",
        {
          "context": context,
          "query": query,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.MultiAnswer, types.MultiAnswer](
        raw,
        lambda x: cast(partial_types.MultiAnswer, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.MultiAnswer, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def OutputQuestion(
        self,
        context: str,question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.AnswerQuestion, types.AnswerQuestion]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "OutputQuestion",
        {
          "context": context,
          "question": question,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.AnswerQuestion, types.AnswerQuestion](
        raw,
        lambda x: cast(partial_types.AnswerQuestion, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.AnswerQuestion, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def QueryRewritePrompt(
        self,
        context: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.RewrittenPrompt, types.RewrittenPrompt]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "QueryRewritePrompt",
        {
          "context": context,
          "query": query,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.RewrittenPrompt, types.RewrittenPrompt](
        raw,
        lambda x: cast(partial_types.RewrittenPrompt, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.RewrittenPrompt, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def QuestionNER(
        self,
        schema: List[str],input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.QNers, types.QNers]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "QuestionNER",
        {
          "schema": schema,
          "input": input,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.QNers, types.QNers](
        raw,
        lambda x: cast(partial_types.QNers, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.QNers, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def QuestionSummary(
        self,
        history: str,question: str,docs: List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.QuestionSummaryAnswer, types.QuestionSummaryAnswer]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "QuestionSummary",
        {
          "history": history,
          "question": question,
          "docs": docs,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.QuestionSummaryAnswer, types.QuestionSummaryAnswer](
        raw,
        lambda x: cast(partial_types.QuestionSummaryAnswer, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.QuestionSummaryAnswer, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def ReferenceGenerator(
        self,
        now: str,content: str,ref: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.RefAnswer, types.RefAnswer]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "ReferenceGenerator",
        {
          "now": now,
          "content": content,
          "ref": ref,
          "query": query,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.RefAnswer, types.RefAnswer](
        raw,
        lambda x: cast(partial_types.RefAnswer, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.RefAnswer, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def RespExtractor(
        self,
        supporting_fact: str,instruction: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.Passage, types.Passage]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "RespExtractor",
        {
          "supporting_fact": supporting_fact,
          "instruction": instruction,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.Passage, types.Passage](
        raw,
        lambda x: cast(partial_types.Passage, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.Passage, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def RespGenerator(
        self,
        memory: str,instruction: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.Answer, types.Answer]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "RespGenerator",
        {
          "memory": memory,
          "instruction": instruction,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.Answer, types.Answer](
        raw,
        lambda x: cast(partial_types.Answer, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.Answer, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def RespJudge(
        self,
        memory: str,instruction: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.Judgement, types.Judgement]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "RespJudge",
        {
          "memory": memory,
          "instruction": instruction,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.Judgement, types.Judgement](
        raw,
        lambda x: cast(partial_types.Judgement, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.Judgement, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def RespReflector(
        self,
        memory: str,instruction: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.Reflection, types.Reflection]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "RespReflector",
        {
          "memory": memory,
          "instruction": instruction,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.Reflection, types.Reflection](
        raw,
        lambda x: cast(partial_types.Reflection, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.Reflection, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def RespVerifier(
        self,
        sub_instruction: str,supporting_fact: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.Verifier, types.Verifier]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "RespVerifier",
        {
          "sub_instruction": sub_instruction,
          "supporting_fact": supporting_fact,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.Verifier, types.Verifier](
        raw,
        lambda x: cast(partial_types.Verifier, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.Verifier, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def RetrieverStaticPlanning(
        self,
        executors: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.STasks, types.STasks]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "RetrieverStaticPlanning",
        {
          "executors": executors,
          "query": query,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.STasks, types.STasks](
        raw,
        lambda x: cast(partial_types.STasks, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.STasks, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def RewriteSubQuery(
        self,
        history_qa: str,question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.RewriteQuery, types.RewriteQuery]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "RewriteSubQuery",
        {
          "history_qa": history_qa,
          "question": question,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.RewriteQuery, types.RewriteQuery](
        raw,
        lambda x: cast(partial_types.RewriteQuery, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.RewriteQuery, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def RewriteSubTaskQuery(
        self,
        content: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.Rewrite, types.Rewrite]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "RewriteSubTaskQuery",
        {
          "content": content,
          "input": input,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.Rewrite, types.Rewrite](
        raw,
        lambda x: cast(partial_types.Rewrite, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.Rewrite, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def SPORetrieval(
        self,
        question: str,mention: str,candis: List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.SPOs, types.SPOs]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "SPORetrieval",
        {
          "question": question,
          "mention": mention,
          "candis": candis,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.SPOs, types.SPOs](
        raw,
        lambda x: cast(partial_types.SPOs, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.SPOs, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def SPORetrievalDecompose(
        self,
        question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.SPODecomposes, types.SPODecomposes]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "SPORetrievalDecompose",
        {
          "question": question,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.SPODecomposes, types.SPODecomposes](
        raw,
        lambda x: cast(partial_types.SPODecomposes, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.SPODecomposes, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def SelfCognition(
        self,
        question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.Cognition, types.Cognition]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "SelfCognition",
        {
          "question": question,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.Cognition, types.Cognition](
        raw,
        lambda x: cast(partial_types.Cognition, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.Cognition, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def SolveQuestion(
        self,
        question: str,history: str,docs: str,knowledge_graph: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.SolveNoSPO, types.SolveNoSPO]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "SolveQuestion",
        {
          "question": question,
          "history": history,
          "docs": docs,
          "knowledge_graph": knowledge_graph,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.SolveNoSPO, types.SolveNoSPO](
        raw,
        lambda x: cast(partial_types.SolveNoSPO, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.SolveNoSPO, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def SolveQuestionNoDocs(
        self,
        question: str,history: str,knowledge_graph: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.SolveNoDocs, types.SolveNoDocs]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "SolveQuestionNoDocs",
        {
          "question": question,
          "history": history,
          "knowledge_graph": knowledge_graph,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.SolveNoDocs, types.SolveNoDocs](
        raw,
        lambda x: cast(partial_types.SolveNoDocs, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.SolveNoDocs, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def SolveQuestionNoSPO(
        self,
        question: str,history: str,docs: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.SolveNoSPO, types.SolveNoSPO]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "SolveQuestionNoSPO",
        {
          "question": question,
          "history": history,
          "docs": docs,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.SolveNoSPO, types.SolveNoSPO](
        raw,
        lambda x: cast(partial_types.SolveNoSPO, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.SolveNoSPO, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def StaticPlanningPrompt(
        self,
        executors: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.STasks, types.STasks]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "StaticPlanningPrompt",
        {
          "executors": executors,
          "query": query,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.STasks, types.STasks](
        raw,
        lambda x: cast(partial_types.STasks, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.STasks, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def SubQuestionSummary(
        self,
        history: str,question: str,knowledge_graph: str,docs: List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.SubQuestionSummaryAnswer, types.SubQuestionSummaryAnswer]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "SubQuestionSummary",
        {
          "history": history,
          "question": question,
          "knowledge_graph": knowledge_graph,
          "docs": docs,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.SubQuestionSummaryAnswer, types.SubQuestionSummaryAnswer](
        raw,
        lambda x: cast(partial_types.SubQuestionSummaryAnswer, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.SubQuestionSummaryAnswer, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def ToughtIterativePlanning(
        self,
        example_executors: str,query: str,context: str,executors: List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.Executor, types.Executor]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "ToughtIterativePlanning",
        {
          "example_executors": example_executors,
          "query": query,
          "context": context,
          "executors": executors,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.Executor, types.Executor](
        raw,
        lambda x: cast(partial_types.Executor, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.Executor, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def ToughtThenAnswer(
        self,
        cur_question: str,questions: str,docs: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.TTA, types.TTA]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "ToughtThenAnswer",
        {
          "cur_question": cur_question,
          "questions": questions,
          "docs": docs,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.TTA, types.TTA](
        raw,
        lambda x: cast(partial_types.TTA, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.TTA, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def WithoutRefGenerator(
        self,
        now: str,content: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.WRG, types.WRG]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []

      raw = self.__runtime.stream_function_sync(
        "WithoutRefGenerator",
        {
          "now": now,
          "content": content,
          "query": query,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlSyncStream[partial_types.WRG, types.WRG](
        raw,
        lambda x: cast(partial_types.WRG, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.WRG, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    


b = BamlSyncClient(DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX)

__all__ = ["b"]