###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
from typing import Any, Dict, List, Optional, Union, TypedDict, Type, Literal
from typing_extensions import NotRequired

import baml_py

from . import types
from .types import Checked, Check
from .type_builder import TypeBuilder


class BamlCallOptions(TypedDict, total=False):
    tb: NotRequired[TypeBuilder]
    client_registry: NotRequired[baml_py.baml_py.ClientRegistry]


class HttpRequest:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager

    
    def DeduceChoice(
        self,
        instruction: str,memory: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "DeduceChoice",
        {
          "instruction": instruction,"memory": memory,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    def DeduceEntail(
        self,
        instruction: str,memory: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "DeduceEntail",
        {
          "instruction": instruction,"memory": memory,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    def DeduceExtractor(
        self,
        instruction: str,memory: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "DeduceExtractor",
        {
          "instruction": instruction,"memory": memory,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    def DeduceJudge(
        self,
        instruction: str,memory: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "DeduceJudge",
        {
          "instruction": instruction,"memory": memory,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    def DeduceMultiChoice(
        self,
        instruction: str,memory: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "DeduceMultiChoice",
        {
          "instruction": instruction,"memory": memory,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    def ExpressionBuilder(
        self,
        now: str,question: str,context: str,error: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "ExpressionBuilder",
        {
          "now": now,"question": question,"context": context,"error": error,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    def LFStaticPlanningPrompt(
        self,
        now: str,case: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "LFStaticPlanningPrompt",
        {
          "now": now,"case": case,"query": query,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    def LogicFromPlan(
        self,
        question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "LogicFromPlan",
        {
          "question": question,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    def MultiHopGenerator(
        self,
        context: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "MultiHopGenerator",
        {
          "context": context,"query": query,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    def OutputQuestion(
        self,
        context: str,question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "OutputQuestion",
        {
          "context": context,"question": question,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    def QueryRewritePrompt(
        self,
        context: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "QueryRewritePrompt",
        {
          "context": context,"query": query,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    def QuestionNER(
        self,
        schema: List[str],input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "QuestionNER",
        {
          "schema": schema,"input": input,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    def QuestionSummary(
        self,
        history: str,question: str,docs: List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "QuestionSummary",
        {
          "history": history,"question": question,"docs": docs,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    def ReferenceGenerator(
        self,
        now: str,content: str,ref: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "ReferenceGenerator",
        {
          "now": now,"content": content,"ref": ref,"query": query,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    def RespExtractor(
        self,
        supporting_fact: str,instruction: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "RespExtractor",
        {
          "supporting_fact": supporting_fact,"instruction": instruction,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    def RespGenerator(
        self,
        memory: str,instruction: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "RespGenerator",
        {
          "memory": memory,"instruction": instruction,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    def RespJudge(
        self,
        memory: str,instruction: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "RespJudge",
        {
          "memory": memory,"instruction": instruction,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    def RespReflector(
        self,
        memory: str,instruction: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "RespReflector",
        {
          "memory": memory,"instruction": instruction,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    def RespVerifier(
        self,
        sub_instruction: str,supporting_fact: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "RespVerifier",
        {
          "sub_instruction": sub_instruction,"supporting_fact": supporting_fact,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    def RetrieverStaticPlanning(
        self,
        executors: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "RetrieverStaticPlanning",
        {
          "executors": executors,"query": query,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    def RewriteSubQuery(
        self,
        history_qa: str,question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "RewriteSubQuery",
        {
          "history_qa": history_qa,"question": question,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    def RewriteSubTaskQuery(
        self,
        content: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "RewriteSubTaskQuery",
        {
          "content": content,"input": input,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    def SPORetrieval(
        self,
        question: str,mention: str,candis: List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "SPORetrieval",
        {
          "question": question,"mention": mention,"candis": candis,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    def SPORetrievalDecompose(
        self,
        question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "SPORetrievalDecompose",
        {
          "question": question,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    def SelfCognition(
        self,
        question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "SelfCognition",
        {
          "question": question,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    def SolveQuestion(
        self,
        question: str,history: str,docs: str,knowledge_graph: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "SolveQuestion",
        {
          "question": question,"history": history,"docs": docs,"knowledge_graph": knowledge_graph,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    def SolveQuestionNoDocs(
        self,
        question: str,history: str,knowledge_graph: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "SolveQuestionNoDocs",
        {
          "question": question,"history": history,"knowledge_graph": knowledge_graph,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    def SolveQuestionNoSPO(
        self,
        question: str,history: str,docs: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "SolveQuestionNoSPO",
        {
          "question": question,"history": history,"docs": docs,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    def StaticPlanningPrompt(
        self,
        executors: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "StaticPlanningPrompt",
        {
          "executors": executors,"query": query,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    def SubQuestionSummary(
        self,
        history: str,question: str,knowledge_graph: str,docs: List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "SubQuestionSummary",
        {
          "history": history,"question": question,"knowledge_graph": knowledge_graph,"docs": docs,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    def ToughtIterativePlanning(
        self,
        example_executors: str,query: str,context: str,executors: List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "ToughtIterativePlanning",
        {
          "example_executors": example_executors,"query": query,"context": context,"executors": executors,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    def ToughtThenAnswer(
        self,
        cur_question: str,questions: str,docs: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "ToughtThenAnswer",
        {
          "cur_question": cur_question,"questions": questions,"docs": docs,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    def WithoutRefGenerator(
        self,
        now: str,content: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "WithoutRefGenerator",
        {
          "now": now,"content": content,"query": query,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    


class HttpStreamRequest:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager

    
    def DeduceChoice(
        self,
        instruction: str,memory: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "DeduceChoice",
        {
          "instruction": instruction,"memory": memory,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    def DeduceEntail(
        self,
        instruction: str,memory: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "DeduceEntail",
        {
          "instruction": instruction,"memory": memory,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    def DeduceExtractor(
        self,
        instruction: str,memory: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "DeduceExtractor",
        {
          "instruction": instruction,"memory": memory,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    def DeduceJudge(
        self,
        instruction: str,memory: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "DeduceJudge",
        {
          "instruction": instruction,"memory": memory,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    def DeduceMultiChoice(
        self,
        instruction: str,memory: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "DeduceMultiChoice",
        {
          "instruction": instruction,"memory": memory,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    def ExpressionBuilder(
        self,
        now: str,question: str,context: str,error: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "ExpressionBuilder",
        {
          "now": now,"question": question,"context": context,"error": error,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    def LFStaticPlanningPrompt(
        self,
        now: str,case: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "LFStaticPlanningPrompt",
        {
          "now": now,"case": case,"query": query,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    def LogicFromPlan(
        self,
        question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "LogicFromPlan",
        {
          "question": question,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    def MultiHopGenerator(
        self,
        context: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "MultiHopGenerator",
        {
          "context": context,"query": query,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    def OutputQuestion(
        self,
        context: str,question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "OutputQuestion",
        {
          "context": context,"question": question,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    def QueryRewritePrompt(
        self,
        context: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "QueryRewritePrompt",
        {
          "context": context,"query": query,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    def QuestionNER(
        self,
        schema: List[str],input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "QuestionNER",
        {
          "schema": schema,"input": input,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    def QuestionSummary(
        self,
        history: str,question: str,docs: List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "QuestionSummary",
        {
          "history": history,"question": question,"docs": docs,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    def ReferenceGenerator(
        self,
        now: str,content: str,ref: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "ReferenceGenerator",
        {
          "now": now,"content": content,"ref": ref,"query": query,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    def RespExtractor(
        self,
        supporting_fact: str,instruction: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "RespExtractor",
        {
          "supporting_fact": supporting_fact,"instruction": instruction,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    def RespGenerator(
        self,
        memory: str,instruction: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "RespGenerator",
        {
          "memory": memory,"instruction": instruction,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    def RespJudge(
        self,
        memory: str,instruction: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "RespJudge",
        {
          "memory": memory,"instruction": instruction,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    def RespReflector(
        self,
        memory: str,instruction: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "RespReflector",
        {
          "memory": memory,"instruction": instruction,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    def RespVerifier(
        self,
        sub_instruction: str,supporting_fact: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "RespVerifier",
        {
          "sub_instruction": sub_instruction,"supporting_fact": supporting_fact,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    def RetrieverStaticPlanning(
        self,
        executors: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "RetrieverStaticPlanning",
        {
          "executors": executors,"query": query,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    def RewriteSubQuery(
        self,
        history_qa: str,question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "RewriteSubQuery",
        {
          "history_qa": history_qa,"question": question,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    def RewriteSubTaskQuery(
        self,
        content: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "RewriteSubTaskQuery",
        {
          "content": content,"input": input,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    def SPORetrieval(
        self,
        question: str,mention: str,candis: List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "SPORetrieval",
        {
          "question": question,"mention": mention,"candis": candis,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    def SPORetrievalDecompose(
        self,
        question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "SPORetrievalDecompose",
        {
          "question": question,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    def SelfCognition(
        self,
        question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "SelfCognition",
        {
          "question": question,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    def SolveQuestion(
        self,
        question: str,history: str,docs: str,knowledge_graph: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "SolveQuestion",
        {
          "question": question,"history": history,"docs": docs,"knowledge_graph": knowledge_graph,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    def SolveQuestionNoDocs(
        self,
        question: str,history: str,knowledge_graph: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "SolveQuestionNoDocs",
        {
          "question": question,"history": history,"knowledge_graph": knowledge_graph,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    def SolveQuestionNoSPO(
        self,
        question: str,history: str,docs: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "SolveQuestionNoSPO",
        {
          "question": question,"history": history,"docs": docs,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    def StaticPlanningPrompt(
        self,
        executors: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "StaticPlanningPrompt",
        {
          "executors": executors,"query": query,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    def SubQuestionSummary(
        self,
        history: str,question: str,knowledge_graph: str,docs: List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "SubQuestionSummary",
        {
          "history": history,"question": question,"knowledge_graph": knowledge_graph,"docs": docs,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    def ToughtIterativePlanning(
        self,
        example_executors: str,query: str,context: str,executors: List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "ToughtIterativePlanning",
        {
          "example_executors": example_executors,"query": query,"context": context,"executors": executors,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    def ToughtThenAnswer(
        self,
        cur_question: str,questions: str,docs: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "ToughtThenAnswer",
        {
          "cur_question": cur_question,"questions": questions,"docs": docs,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    def WithoutRefGenerator(
        self,
        now: str,content: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return self.__runtime.build_request_sync(
        "WithoutRefGenerator",
        {
          "now": now,"content": content,"query": query,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    


__all__ = ["HttpRequest", "HttpStreamRequest"]