###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing_extensions import TypeAlias
from typing import Dict, Generic, List, Literal, Optional, TypeVar, Union


T = TypeVar('T')
CheckName = TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str

class Checked(BaseModel, Generic[T,CheckName]):
    value: T
    checks: Dict[CheckName, Check]

def get_checks(checks: Dict[CheckName, Check]) -> List[Check]:
    return list(checks.values())

def all_succeeded(checks: Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))



class Answer(BaseModel):
    answer: str

class AnswerQuestion(BaseModel):
    answer: str

class Builder(BaseModel):
    python_code: str
    not_known: bool

class Choice(BaseModel):
    choice: str
    no_available_information: bool

class Cognition(BaseModel):
    is_cognition_question: bool

class Entail(BaseModel):
    entail: str
    no_available_information: bool

class Executor(BaseModel):
    name: str
    arguments: List["ExecutorArgument"]
    thought: str

class ExecutorArgument(BaseModel):
    name: str
    instruction: str

class Extractor(BaseModel):
    extractor: str
    no_relevant_information: bool

class Judge(BaseModel):
    assessable: bool
    no_available_information: bool

class Judgement(BaseModel):
    answer: bool

class LFStaticPlan(BaseModel):
    idea: str
    step: str
    action: str

class LFStaticPlanning(BaseModel):
    python_code: str
    not_known: bool

class LFStaticPlans(BaseModel):
    plans: List["LFStaticPlan"]

class Multi(BaseModel):
    option: str
    no_available_information: bool

class MultiAnswer(BaseModel):
    thought: str
    answer: str

class Passage(BaseModel):
    passage: str

class Plan(BaseModel):
    step: str
    action: str

class Plans(BaseModel):
    plans: List["Plan"]

class QNer(BaseModel):
    name: str
    category: str

class QNers(BaseModel):
    output: List["QNer"]

class QuestionSummaryAnswer(BaseModel):
    answer: str

class RefAnswer(BaseModel):
    answer: str
    reference_id: Optional[str] = None
    internal_knowledge: bool

class Reflection(BaseModel):
    thought_questions: List[str]

class Rewrite(BaseModel):
    rewritten_question: str

class RewriteQuery(BaseModel):
    rewritten_question: str

class RewrittenPrompt(BaseModel):
    query: bool

class SPODecompose(BaseModel):
    step: str
    action: str

class SPODecomposes(BaseModel):
    spos: List["SPODecompose"]

class SPOs(BaseModel):
    spos: List[str]

class SPPArgument(BaseModel):
    name: str
    instruction: str

class STask(BaseModel):
    task_id: int
    executor: str
    dependent_task_ids: List[int]
    args: List["SPPArgument"]

class STasks(BaseModel):
    tasks: List["STask"]

class Solve(BaseModel):
    answer: str

class SolveNoDocs(BaseModel):
    answer: str

class SolveNoSPO(BaseModel):
    answer: str

class SubQuestionSummaryAnswer(BaseModel):
    answer: str

class TTA(BaseModel):
    thought: str
    answer: str

class Verifier(BaseModel):
    answer: str
    answered: bool

class WRG(BaseModel):
    answer: str
